datasets:
  unnatural_instruction:
    data_type: text
    build_info:
      ann_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/unnatural_instructions/filtered_unnatural_instruction.json