datasets:
  flickr_CaptionToPhrase:
    data_type: images
    build_info:
      image_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/filtered_flikcr/images
      ann_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/filtered_flikcr/captiontobbox.json
