datasets:
  invrefcocog:
    data_type: images
    build_info:
      image_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/coco/images
      ann_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/refcoco_annotations
      dataset: invrefcocog
      splitBy: umd