model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/data00/hc/checkpoint/huggingface/models--meta-llama--Llama-2-7b-hf"
  ckpt: "/home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/checkpoint/multitask_finetune_0324/20240324231049/checkpoint_49.pth"
  lora_r: 64
  lora_alpha: 16

datasets:
  refdet_v3:
    vis_processor:
      test:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      test:
        name: "blip_caption"
    max_new_tokens: 20
    batch_size: 10

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/results/multitask_0324

  

  

