datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/textcaps/train_images
      ann_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/minigpt_ft_dataset/textcaps/TextCaps_0.1_train.json


