model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/data00/hc/checkpoint/huggingface/models--meta-llama--Llama-2-7b-hf"
  ckpt: "/home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/checkpoint/20240310190/checkpoint_37.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  refcoco:
    eval_file_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/chengguan_dataset/refdet_v1.1
    img_path: /data00/hc/dataset/chengguan/kejibu/trainval/JPEGImages
    max_new_tokens: 20
    batch_size: 10


run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/hc/workspace/real_graduate/MiniGPT-v2-chengguan/results/test_refdet_v1_0312/test1.1/

  

  

